version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # AMQP protocol port
      - "15672:15672"    # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  service-a:
    build: ./service-a
    ports:
      - "3001:3001"
    environment:
      RABBITMQ_URL: amqp://rabbitmq

  service-b:
    build: ./service-b
    ports:
      - "3002:3002"
    environment:
      RABBITMQ_URL: amqp://rabbitmq
